sudo: false
language: node_js
node_js:
  - "7"
git:
  depth: 1
branches:
  only:
  - master
cache:
  timeout: 1800
  yarn: true
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false