version: 2.1

commands:
  run-tests:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Source
          command: npm run test

jobs:
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - run-tests

  node-lts:
    docker:
      - image: circleci/node:lts
    steps:
      - run-tests

workflows:
  node-multi-build:
    jobs:
    - node-latest
    - node-lts
  version: 2
